# Exclusive OR with Keras

In [1]:
# NOTE: This is required, else the results of the model training will differ vastly.
from __future__ import absolute_import, division, print_function, unicode_literals

import numpy as np
import tensorflow as tf

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD

In [2]:
print(tf.version.VERSION)

2.0.0-beta1


In [3]:
x_train = np.array([[0, 0],
                    [0, 1],
                    [1, 0],
                    [1, 1]])

y_train = np.array([[0],
                    [1],
                    [1],
                    [0]])

In [4]:
def create_model():
# The fully connected hidden layer will have 100 neurons.
    num_neurons = 10

    model = Sequential([
        Dense(num_neurons, activation='relu', input_dim=2),
        # The output layer has one neuron to output a single binary classification value (0 or 1).
        Dense(1, activation='sigmoid')
    ])
    sgd = SGD(0.1)
    model.compile(loss='binary_crossentropy', 
                  optimizer=sgd,
                  metrics=['accuracy'])
    return model

# Alternatively, we can use add each layer independently.
# model.add(Dense(num_neurons, activation='relu', input_dim=2))
# model.add(Dense(1, activation='sigmoid'))

In [5]:
model = create_model()
# Overview of the network parameter and number of weights at each stage.
# 10 neurons, each with two weights (one for each value in the input vector), 
# and one weight for the bias gives you 30 weights to learn.
# The output layer has a weight for each of the 10 neurons in the first layer 
# and one bias weight for a total of 11 in that layer.
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                30        
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 41
Trainable params: 41
Non-trainable params: 0
_________________________________________________________________


In [6]:
model.predict(x_train)

array([[0.5       ],
       [0.28757626],
       [0.5413843 ],
       [0.25403112]], dtype=float32)

In [7]:
model.fit(x_train, y_train, epochs=100)

W1221 14:46:44.952793 4450168256 deprecation.py:323] From /usr/local/lib/python3.7/site-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Train on 4 samples
Epoch 1/100
4/4 [==============================] - 0s 17ms/sample - loss: 0.7115 - accuracy: 0.7500
Epoch 2/100
4/4 [==============================] - 0s 546us/sample - loss: 0.6995 - accuracy: 0.5000
Epoch 3/100
4/4 [==============================] - 0s 394us/sample - loss: 0.6887 - accuracy: 0.5000
Epoch 4/100
4/4 [==============================] - 0s 2ms/sample - loss: 0.6798 - accuracy: 0.5000
Epoch 5/100
4/4 [==============================] - 0s 2ms/sample - loss: 0.6726 - accuracy: 0.5000
Epoch 6/100
4/4 [==============================] - 0s 2ms/sample - loss: 0.6659 - accuracy: 0.5000
Epoch 7/100
4/4 [==============================] - 0s 1ms/sample - loss: 0.6597 - accuracy: 0.5000
Epoch 8/100
4/4 [==============================] - 0s 607us/sample - loss: 0.6542 - accuracy: 0.5000
Epoch 9/100
4/4 [==============================] - 0s 515us/sample - loss: 0.6489 - accuracy: 0.5000
Epoch 10/100
4/4 [==============================] - 0s 560us/sample - loss: 0.643

Epoch 82/100
4/4 [==============================] - 0s 484us/sample - loss: 0.4996 - accuracy: 0.7500
Epoch 83/100
4/4 [==============================] - 0s 558us/sample - loss: 0.4985 - accuracy: 0.7500
Epoch 84/100
4/4 [==============================] - 0s 839us/sample - loss: 0.4965 - accuracy: 0.7500
Epoch 85/100
4/4 [==============================] - 0s 344us/sample - loss: 0.4949 - accuracy: 0.7500
Epoch 86/100
4/4 [==============================] - 0s 588us/sample - loss: 0.4945 - accuracy: 0.7500
Epoch 87/100
4/4 [==============================] - 0s 519us/sample - loss: 0.4932 - accuracy: 0.7500
Epoch 88/100
4/4 [==============================] - 0s 802us/sample - loss: 0.4915 - accuracy: 1.0000
Epoch 89/100
4/4 [==============================] - 0s 371us/sample - loss: 0.4901 - accuracy: 1.0000
Epoch 90/100
4/4 [==============================] - 0s 503us/sample - loss: 0.4888 - accuracy: 1.0000
Epoch 91/100
4/4 [==============================] - 0s 646us/sample - loss: 0.4879

In [8]:
model.predict_classes(x_train)

array([[0],
       [1],
       [1],
       [0]], dtype=int32)

In [9]:
model.predict(x_train)

array([[0.49407762],
       [0.5063816 ],
       [0.79505247],
       [0.26788902]], dtype=float32)

# Saving the trained model

In [13]:
# Save the model.
model.save('model.h5')

!ls -a 

# Recreate the exact same model purely from the file.
new_model = tf.keras.models.load_model('model.h5')
new_model.predict(x_train)

.                  01_neuron.ipynb    04_mnist.ipynb     model.h5
..                 02_or_gate.ipynb   basic_model.json
.ipynb_checkpoints 03-xor-keras.ipynb basic_weights.h5


array([[0.49407762],
       [0.5063816 ],
       [0.79505247],
       [0.26788902]], dtype=float32)

# References

https://blog.thoughtram.io/machine-learning/2016/11/02/understanding-XOR-with-keras-and-tensorlow.html